plusOne/action/urls.py
from django.urls import path
from .views import home, activity, search, add, stop, tripdetails, profile, edit

urlpatterns = [
    path("", home, name="home"),
    path("activity/", activity, name="activity"),
    path("search/", search, name="search"),
    path("search/add/", add, name="add"),
    path("activity/stop/<int:id>", stop, name="stop"),
    path("profile/", profile, name="profile"),
    path("profile/edit/", edit, name="edit"),
    path("search/trip/<int:id>", tripdetails, name="tripdetails")
]

plusOne/plusOne/urls.py
from django.contrib import admin
from django.urls import path, include

import cas.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('action.urls')),
    path('', include('cas_auth.urls')),
    path('accounts/login/', cas.views.login),
    path('accounts/logout/', cas.views.logout),
]

plusOne/action/models.py
from django.db import models
from django.utils import timezone
from datetime import datetime, timedelta, date

def def_journey_time():
    dt = timezone.now() + timedelta(minutes=10)
    return dt.time().strftime("%H:%M")


TAG_LIST = [
    ['airport', 'Rajiv Gandhi International Airport'],
    ['railway-secunderabad', 'Secunderabad Railway Station'],
    ['railway-lingam', 'Lingampally Railway Station'],
    ['railway-begumpet', 'Begumpet Railway Station'],
    ['railway-nampally', 'Hyderabad Deccan Railway Station (Nampally)'],
    ['bus-mg', 'Mahatma Gandhi Bus Station'],
    ['college','IIIT Hyderabad Campus']
]

class Trip(models.Model):
    source = models.CharField(max_length = 100, choices = TAG_LIST, default = 'college')
    destination = models.CharField(max_length = 100, choices = TAG_LIST, default = 'airport')
    journey_date = models.DateField(default = timezone.now)
    journey_time = models.TimeField(default = def_journey_time)
    is_active = models.BooleanField(default = False)
    owner = models.CharField(max_length = 100, null = True, blank = True)
    minima = models.IntegerField(default = 30)
    maxima = models.IntegerField(default = 20)

class Profile(models.Model):
    first_name = models.CharField(max_length = 100, default = '')
    last_name = models.CharField(max_length = 100, default = '')
    email = models.EmailField(max_length = 100, default = '')

plusOne/action/forms.py
from django import forms
from .models import Trip, Profile
import datetime
from django.utils import timezone

from django.contrib.auth.models import User


class EditForm(forms.ModelForm):
    
    class Meta:
        model = Profile
        fields = [
            'first_name',
            'last_name',
            'email'
        ]
        labels = {
            'first_name': 'YOUR NAME?',
            'last_name': 'PHONE NUMBER?',
            'email': 'EMAIL ADDRESS?'
        }
        widgets = {
            'first_name': forms.TextInput(attrs = {'class': 'form-control py-4 mb-4', 'autocomplete': 'off'}),
            'last_name': forms.TextInput(attrs = {'class': 'form-control py-4 mb-4', 'autocomplete': 'off'}),
            'email': forms.TextInput(attrs = {'class': 'form-control py-4 mb-4', 'autocomplete': 'off'})
        }


class TripForm(forms.ModelForm):
    class Meta:
        model = Trip
        fields = [
            "destination",
            "source",
            "journey_date",
            "journey_time",
            "minima",
            "maxima"
        ]
        labels = {
            "source": "WHERE FROM?",
            "destination": "WHERE TO?",
            "journey_date": "WHEN?",
            "journey_time": "",
            "minima": "I AM WILLING TO START BETWEEN",
            "maxima" : "AND"
        }
        widgets = {
            "source": forms.Select(attrs = {'class': 'form-dd py-3 pl-2 mb-3', 'autocomplete': 'off'}),
            "destination": forms.Select(attrs = {'class': 'form-dd py-3 pl-2 mb-3', 'autocomplete': 'off'}),
            "journey_date": forms.DateInput(attrs = {'class': 'form-control py-4 mb-3 dt-gray', 'autocomplete': 'off'}),
            "journey_time": forms.TimeInput(attrs = {'class': 'form-control py-4 mb-3 dt-gray', 'autocomplete': 'off'}),
            "minima": forms.NumberInput(attrs = {'class': 'form-control py-4 mb-1 dt-gray', 'autocomplete': 'off'}),
            "maxima": forms.NumberInput(attrs = {'class': 'form-control py-4 mb-1 dt-gray', 'autocomplete': 'off'})
        }

plusOne/action/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from .models import Trip
from .forms import TripForm, EditForm
import datetime
import time
import json
from django.contrib.auth.models import User
import logging
import re
from django.contrib import messages
logger = logging.getLogger(__name__)

TAG_DICT = {
    'airport': 'Rajiv Gandhi International Airport',
    'railway-secunderabad': 'Secunderabad Railway Station',
    'railway-lingam': 'Lingampally Railway Station',
    'railway-begumpet': 'Begumpet Railway Station',
    'railway-nampally': 'Hyderabad Deccan Railway Station (Nampally)',
    'bus-mg': 'Mahatma Gandhi Bus Station',
    'college':'IIIT Hyderabad Campus'
}

@login_required
def home(request, *args, **kwargs):
    if not request.user.first_name:
        return redirect('/register/')
    
    form = TripForm(request.POST or None)
    if request.method == 'POST':
        source = request.POST.get('source')
        destin = request.POST.get('destination')
        j_time = request.POST.get('time')
        j_date = request.POST.get('date')
        minima = request.POST.get('minima')
        maxima = request.POST.get('maxima')

        # form validation
        errorMessages = {}
        
        # clean_source
        if destin == source:
            errorMessages['source'] = "Invalid! Source cannot be same as Destination!"

        # clean_journey_time
        journey_datetime = datetime.datetime.combine(
            datetime.datetime.strptime(j_date, '%d/%m/%Y').date(), 
            datetime.datetime.strptime(j_time, '%H:%M').time()
        )
        if journey_datetime < timezone.now():
            errorMessages['journey_time'] = "Invalid Time!"
        
        response = JsonResponse(errorMessages)

        if len(errorMessages) == 0:
            request.session['data'] = {
                "source" : source,
                "destination" : destin,
                "journey_date" : j_date,
                "journey_time" : j_time,
                "minima" : str(minima),
                "maxima" : str(maxima)
            }
        else:
           response.status_code = 403 

        return response

    context = {
        "form" : form
    }
    return render(request, "home.html", context)


@login_required
def activity(request, *args, **kwargs):
    trips = Trip.objects.filter(owner = request.user.username)
    object_list=[]
    for trip in trips:
        if datetime.datetime.combine(trip.journey_date, trip.journey_time) < datetime.datetime.now():
            trip.delete()
            continue
        object_list.append(
            {
                "id" : trip.id,
                "source" : TAG_DICT[trip.source],
                "destination" : TAG_DICT[trip.destination],
                "journey_date" : trip.journey_date.strftime("%d/%m/%Y"),
                "journey_time" : trip.journey_time.strftime("%H:%M"),
                "is_active" : trip.is_active
            })
    object_list =  sorted(object_list, key = lambda i : (i['journey_date'],i['journey_time']),reverse=False)
    context = {
        'trips': object_list,
        'populated': len(object_list)
    }
    return render(request, "activity.html", context)

@login_required
def profile(request, *args, **kwargs):
    print(request.user.first_name)
    context={
        'user_list' : request.user
    }
    return render(request, 'profile.html', context)

@login_required
def stop(request, id):
    trip = Trip.objects.get(id = id)
    logger.warning('entered stop')
    logger.warning(trip.is_active)
    trip.is_active = False
    trip.save()
    return redirect("activity")

@login_required
def edit(request, *args, **kwargs):
    form = EditForm(request.POST or None, instance = request.user)
    if request.method == 'POST':
        if form.is_valid():
            temp_list=form.cleaned_data
            temp_name=temp_list.get('first_name')
            temp_num=temp_list.get('last_name')
            temp_email=temp_list.get('email')
            x=re.findall("[0-9]", temp_num)
            if len(x) == 10 :
                request.user.first_name = temp_name
                request.user.last_name = temp_num
                request.user.email = temp_email
                request.user.save()
                return redirect('/profile')
            else:
                messages.info(request, 'Enter Valid Phone Number')
                return render(request, 'edit.html', {'form' : form})
        else:
            messages.info(request, 'Enter valid email address')
            return render(request, 'edit.html', {'form' : form})       
    context = {
        'form': form
    }
    print("yes")
    return render(request, 'edit.html', context)


@login_required
def search(request, *args, **kwargs):
    search_query = request.session.get('data', {})
    source_query = search_query.get("source")
    destination_query = search_query.get("destination")
    date_query = search_query.get("journey_date")
    date_query = datetime.datetime.strptime(date_query, "%d/%m/%Y").date()
    time_query = search_query.get("journey_time")
    time_query = datetime.datetime.strptime(time_query, "%H:%M").time()
    min_query = float(search_query.get("minima"))
    max_query = float(search_query.get("maxima"))
    dt_query = datetime.datetime.combine(date_query, time_query)
    dt_query_min = dt_query - datetime.timedelta(minutes = min_query)
    dt_query_max = dt_query + datetime.timedelta(minutes = max_query)
    trips = Trip.objects.filter(
        source=source_query,
        destination=destination_query,
        is_active=True).exclude(owner=request.user.username)
    object_list = []
    for trip in trips:
        dt = datetime.datetime.combine(trip.journey_date, trip.journey_time)
        if dt < datetime.datetime.now():
            trip.delete()
            continue
        if dt >= dt_query_min and dt <= dt_query_max:
            object_list.append({
                    "id" : trip.id,
                    "source" : TAG_DICT[trip.source],
                    "destination" : TAG_DICT[trip.destination],
                    "journey_date" : trip.journey_date.strftime("%d/%m/%Y"),
                    "journey_time" : trip.journey_time.strftime("%H:%M"),
                    "is_active" : True,
                    "owner" : trip.owner,
                })
    def func_sort(i): 
        x1 = int(time_query.strftime("%H%M"))
        y2 = int(datetime.datetime.strptime(i['journey_time'], "%H:%M").time().strftime("%H%M"))
        d1 = int(x1/100) - int(y2/100)
        d2 = int(y2/100) - int(x1/100)
        if d1 >= 1:
            y2 = y2 + 40*d1
        if d2 >= 1:
            x1 = x1 + 40*d2
        return i['journey_date'],abs(x1-y2)
    object_list =  sorted(object_list, key = func_sort,reverse=False)
    context = {
        "object_list": object_list,
        "populated": len(object_list)
    }
    return render(request, "search.html", context)

@login_required
def add(request, *args, **kwargs):
    search_query = request.session.get("data", {})
    source_query = search_query.get("source")
    destination_query = search_query.get("destination")
    date_query = search_query.get("journey_date")
    date_query = datetime.datetime.strptime(date_query, "%d/%m/%Y").date()
    time_query = search_query.get("journey_time")
    time_query = datetime.datetime.strptime(time_query, "%H:%M").time()
    Trip.objects.create(
        source = source_query,
        destination = destination_query,
        journey_date = date_query,
        journey_time = time_query,
        is_active = True,
        owner = request.user.username
    )
    return redirect("/")


@login_required
def tripdetails(request, id):
    trip = Trip.objects.get(id = id)
    owner = User.objects.get(username = trip.owner)

    context = {
        "owner_name": owner.first_name,
        "owner_contact": owner.last_name,
        "source" : TAG_DICT[trip.source],
        "destination" : TAG_DICT[trip.destination],
        "journey_date" : trip.journey_date.strftime("%d/%m/%Y"),
        "journey_time" : trip.journey_time.strftime("%H:%M"),
    }
    return render(request, 'tripdetails.html', context)

plusOne/action/templates/activity.html
{% extends "base.html" %}

{% block head %}
<title> +1 | My Trips </title>
{% endblock %}

{% block body %}
<div class="container reg-header fin-h text-center pt-5"> Upcoming trips </div>
<div class="container pt-5 mb-5">
    {% if not populated %}
        <div class="not-populated-banner text-center p-5">
            No trips found :(
        </div>
    {% endif %}
    {% for trip in trips %}
    <div class="container search-result-item card home-card p-5 mt-5 shadow-lg">
        <div class="search-result-item-heading-label pt-3"> TO </div>
        <h4 class="search-result-item-heading">{{ trip.destination }}</h4>
        <div class="search-result-item-heading-label pt-3"> FROM </div>
        <h4 class="search-result-item-heading">{{ trip.source }}</h4>
        <p class="info pt-3">{{ trip.journey_date }}, {{ trip.journey_time }}</p>
        <br><br>
        {% if trip.is_active %}
        <form action="stop/{{ trip.id }}">
            <button class="btn btn-outline-danger outline-btn" type="submit"> Stop accepting requests </button>
        </form>
        {% endif %}
    </div>
    {% endfor %}
</div>

{% endblock %}

plusOne/action/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.1/js/tempusdominus-bootstrap-4.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.1/css/tempusdominus-bootstrap-4.min.css" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Jost:ital,wght@0,400;0,500;1,600&display=swap">
    <link rel="stylesheet" type="text/css" href="{% static 'action/style.css' %}">
    {% block head %} {% endblock %}
</head>
<nav id="main-nav" class="navbar navbar-expand-md navbar-dark navbar-black fixed-top bg-dark">
    <a href="/">
    <img class="po-icon" src="{% static 'action/po_logo.png'%}">
    </a>
    <div class="ml-auto btn-container">
        {% if not hidemy %}
        <form class="form-inline my-2" action="/activity/">
            <button class="btn btn-outline-success outline-btn nav-btn mx-2" type="submit"> MY TRIPS </button>
        </form>
        {% endif %}
        {% if not hidemy %}
        <form class="form-inline my-2" action="/profile/">
            <button class="btn btn-outline-warning outline-btn nav-btn mx-2" type="submit"> MY PROFILE </button>
        </form>
        {% endif %}
        <form class="form-inline my-2" action="/accounts/logout/">
            <button class="btn btn-outline-primary outline-btn nav-btn mx-2" type="submit"> LOG OUT </button>
        </form>
    </div>
</nav>
<body class="main-bg">
    <div class="container-fluid centered" style="padding-top: 70px;">
        {% block body %} {% endblock %}
    </div>
</body>
<script>
var navbar = document.getElementById('main-nav');
window.onscroll = () => { 
    if(window.scrollY <= 75) {
        navbar.classList.add('navbar-black');
        navbar.classList.remove('solid-nav');
    } else {
        navbar.classList.add('solid-nav');
        navbar.classList.remove('navbar-black');
    }
};
</script>
</html>

plusOne/action/templates/edit.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Jost:ital,wght@0,400;0,500;1,600&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'action/style.css' %}">
    <title> +1 | Edit Profile </title>
</head>
<body class="main-bg">
    <div class="container-fluid mt-5 centered">
        <div class="container reg-header pre-h pt-5 text-left"> Edit Profile </div>
        <div class="container card home-card p-5 shadow-lg">
            <form id="reg" method="POST"> {% csrf_token %}
                <label class="ml-1"> {{ form.first_name.label }} </label>
                {{ form.first_name }}
                <label class="ml-1"> {{ form.last_name.label }} </label>
                {{ form.last_name }}
                <label class="ml-1"> {{ form.email.label }} </label>
                {{ form.email }}
                <button type="submit" class="btn btn-outline-warning outline-btn p-2 px-4 mt-4"> SUBMIT </button>
            </form>
            <div>
                {% for message in messages %}
                <h4>{{message}}</h4>
                {% endfor %}
            </div>
        </div>
    </div>
</body>
</html>

plusOne/action/templates/home.html
{% extends 'base.html' %}

{% block head %}
<title> +1 | Home </title>
{% endblock %}

{% block body %}
<div class="container reg-header fin-h text-left pt-4"> Ready to go? </div>
<div class="container card home-card p-4 mb-5 mt-5 shadow-lg" action="search/">
    <form id="trip" method="POST"> {% csrf_token %}
        <div id="places-container">
            <label class="ml-1"> {{ form.source.label }} </label>
            {{ form.source }}<br/>
            <label class="ml-1"> {{ form.destination.label }} </label>
            {{ form.destination }}
        </div>
        <div id="datetime-container">
            <label class="ml-1" id="date-chooser"> {{ form.journey_date.label }} </label>
            <div class="form-row">
                <div class="col-lg mb-2">
                    <input type="text" class="form-control dt-gray datetimepicker-input" autocomplete="off" id="datefield" data-toggle="datetimepicker" data-target="#datefield"/>
                </div>
                <div class="col-md-4"> 
                    <input type="text" class="form-control dt-gray datetimepicker-input" autocomplete="off" id="timefield" data-toggle="datetimepicker" data-target="#timefield"/>
                </div>
            </div>
        </div>
        <div id="extrema-container">
            <label class="ml-1 pt-3"> I'M FINE WITH STARTING </label>
            <div class="form-row">
                <div class="col"> 
                    {{ form.minima }} 
                    <div class="text-right">
                        <label class="ml-1 "> MINS BEFORE </label> 
                    </div>
                </div>
                <label class="p-3"> OR </label>
                <div class="col">
                    {{ form.maxima }}
                    <div class="text-right">
                        <label class="ml-1 "> MINS AFTER </label> 
                    </div>
                </div>
            </div>
        </div>
        <button id="home-submit" class="btn btn-outline-danger outline-btn p-2 px-4 mt-4" type="button"> GO! </button>
    </form>
</div>
<script type="text/javascript">
    $(function () {
        var dt = new Date();
        $('#timefield').datetimepicker({
            format: 'HH:mm',
            defaultDate: moment({
                hour: dt.getHours(),
                minute: dt.getMinutes()
            }).add(10, 'm')
        });
    });
    $(function () {
        var dt = new Date();
        $('#datefield').datetimepicker({
            format: 'DD/MM/YYYY',
            defaultDate: moment({
                day: dt.getDate(),
                month: dt.getMonth(),
                year: dt.getFullYear()
            })
        });
    });
    $('#home-submit').click(function() {
        $.ajax({
            url: "/",
            type: "POST",
            data: {
                source: $('#id_source').find(':selected').attr('value'),
                destination: $('#id_destination').find(':selected').attr('value'),
                time: $('#timefield').val(),
                date: $('#datefield').val(),
                minima: $('#id_minima').val(),
                maxima: $('#id_maxima').val(),
                csrfmiddlewaretoken: '{{ csrf_token }}'
            },
            dataType: "html",
            success: function() {
                window.location.href = '/search'
            },
            error: function(data) {
                var jsonResponse = JSON.parse(data.responseText)
                function flashError(target, message) {
                    var container = document.getElementById(target + '-container')
                    if (!(container.classList.contains('error-bg'))) {
                        container.classList.add('error-bg', 'p-2', 'my-1');
                        $('#' + target + '-container').append('<label id='+target+'-error class="ml-1 error-fg">'+message+'</label>');
                    }
                }

                function killError(target) {
                    document.getElementById(target + '-container').classList.remove('error-bg', 'p-2', 'my-1');
                    $('#' + target + '-error').remove();
                }


                if(jsonResponse.hasOwnProperty('source')) {
                    flashError('places', jsonResponse.source);
                } else {
                    killError('places');
                }

                if(jsonResponse.hasOwnProperty('journey_time')) {
                    flashError('datetime', jsonResponse.journey_time);
                } else {
                    killError('datetime');
                }
            }
        });
    });
</script>

{% endblock %}

plusOne/action/templates/profile.html
{% extends 'base.html' %}

{% block head %}
<title> +1 | My Trips </title>
{% endblock %}

{% block body %}
<div class="container reg-header fin-h text-center pt-5"> My Profile </div>
<div class="container search-result-item card home-card p-5 mt-5 shadow-lg">
    <div class="search-result-item-heading-label pt-3"> NAME </div>
    <h4 class="search-result-item-heading">{{ user_list.first_name }}</h4>
    <div class="search-result-item-heading-label pt-3"> PHONE NUMBER </div>
    <h4 class="search-result-item-heading">{{ user_list.last_name }}</h4>
    <div class="search-result-item-heading-label pt-3"> EMAIL ADDRESS </div>
    <h4 class="search-result-item-heading">{{ user_list.email }}</h4>
    <br><br>
    <form action="/profile/edit/">
        <button class="btn btn-outline-danger outline-btn" type="submit"> Edit Profile </button>
    </form>
</div>


{% endblock %}

plusOne/action/templates/search.html
{% extends "base.html" %}

{% block head %}
<title> +1 | Search </title>
{% endblock %}

{% block body %}
<div class="container reg-header fin-h text-center pt-5"> Active trips </div>
<div class="container overflow-hidden pt-5">
    <div class="container overflow-auto centered">
        {% if not populated %}
        <div class="not-populated-banner text-center p-5">
            No trips found :(
        </div>
        {% endif %}
        {% for object in object_list %}
            {% if forloop.counter0|divisibleby:3 %}
                {% if forloop.counter0 != 0 %}
                    </div>
                {% endif %}
                <div class="row py-2">
            {% endif %}
        <div class="col m-2">
        <section class="search-result-item home-card shadow-lg">
            <div class="row">
                <div class="col">
                    <p class="search-dt s-date">{{ object.journey_date }}
                    <h1 class="search-dt s-time">{{ object.journey_time }}</h1>
                    <div class="search-result-item-heading-label pt-3"> TO </div>
                    <h4 class="search-result-item-heading">{{ object.destination }}</h4>
                    <div class="search-result-item-heading-label pt-3"> FROM </div>
                    <h4 class="search-result-item-heading">{{ object.source }}</h4>
                </div>
                <div class="col-xs px-3 text-right">
                    <form action="trip/{{ object.id }}" method="POST"> {% csrf_token %}
                        <button class="btn btn-outline-danger outline-btn btn-md" >+1</button>
                    </form>
                </div>
            </div>
        </section>
        </div>
        {% endfor %}
        </div>

    </div>
    <div class="centered">
        <form action="add/">
            <button type="submit" class="btn btn-outline-info outline-btn mt-5 mb-5"> MAKE A NEW TRIP </button>
        </form>
    </div>
</div>
{% endblock %}

plusOne/action/templates/tripdetails.html
{% extends "base.html" %}

{% block head %}
<title> +1 | Contact </title>
{% endblock %}

{% block body %}

<div class="container search-result-item card home-card p-5 mt-5 shadow-lg">
    <div class="search-result-item-heading-label"> CONTACT </div>
    <h2 class="search-result-item-heading">{{ owner_name }}</h2>
    <h2 class="search-result-item-heading">{{ owner_contact }}</h2>
    <br/><br/>
    <div class="search-result-item-heading-label pt-3"> TO </div>
    <h4 class="search-result-item-heading">{{ destination }}</h4>
    <div class="search-result-item-heading-label pt-3"> FROM </div>
    <h4 class="search-result-item-heading">{{ source }}</h4><br/>
    <h2 class="search-result-item-heading-label">{{ journey_date }}, {{ journey_time }}</h2>
    <div class="pt-5">
        <button onclick="goBack()" class="btn btn-outline-warning outline-btn"> < RETURN TO SEARCH </button>
    </div> 
</div>

<script>
    function goBack() {
      window.history.back();
    }
</script>
{% endblock %}